name: Data Engineering Pipeline

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]
  workflow_dispatch: # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5445:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - "2181:2181"
        env:
          ZOOKEEPER_CLIENT_PORT: "2181"
          ZOOKEEPER_TICK_TIME: "2000"

      kafka:
        image: confluentinc/cp-kafka:6.2.0
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "echo 'Kafka is up'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Database Setup
        run: python storage/script.py

      - name: Wait for Kafka
        run: |
          echo "Waiting for Kafka..."
          for i in {1..20}; do
              nc -z localhost 9092 && echo "Kafka is up" && break
              sleep 5
          done

      - name: Run Kafka Consumer (background)
        run: nohup python consumer/consumer.py &

      - name: Run Kafka Producer
        run: python producer/producer.py
